# Uncomment to enable encoder
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Uncomment the following line to enable the Lily58 OLED Display
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

CONFIG_ZMK_KEYBOARD_NAME="yisenKeyboard58"

CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_SLEEP=y

# Set split role to central to enable USB and other features
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_ZMK_SPLIT=y

# Enable pointing device support
CONFIG_ZMK_POINTING=y

# USB Configuration for split setup
CONFIG_ZMK_USB=y

# Comment out below to increase battery.  This is on due to some computers having bad bluetooth range.
#CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

CONFIG_NICE_OLED_SHOW_SLEEP_ART_ON_IDLE=y
CONFIG_NICE_OLED_SHOW_SLEEP_ART_ON_SLEEP=y
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_GEM=n
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_CAT=n
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_HEAD=y

CONFIG_NICE_OLED_WIDGET_WPM_BONGO_CAT=n

# CONFIG_NICE_OLED_WIDGET_WPM_GRAPH=y
CONFIG_NICE_OLED_WIDGET_WPM_LUNA=n
